### PR TITLE
Feature/fix layout

### LINKED ISSUE #107: Revisit layouting
- Fix navbar
- Fix tables not having scrollbars
- Fix filters

# Review

- [ ] Code is written
- [ ] Tests (if necessary) are written
- [ ] Code is documented (either in documentation itself or in code)
- [ ] Code is reviewed
- [ ] Must implement functionality specified in the ticket and in line with the design specifications (e.g. wireframes)
- [ ] Build is successful (including all tests passed)
- [ ] Deployment to staging works
- [ ] Manual testing on staging by peer

### PR DESCRIPTION
**Pull request by Tugark**
Fixes #107 

* Fixed navbar so layout does not break on mobile
* Made GoOnline button a `<Fab>`
* Fixed tables not having scrollbars by adding some fixed minimum widths
* Fixed filters and layouting in tables
* Removed time from our dateformat - I think we can spare this space :)

### CODE REVIEW

File: src/components/shared/navbar/NavBarUserActions.tsx [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+import LoginIcon from '@mui/icons-material/Login'
+
+const NavBarUserActions = () => {
+  const { email, signOut } = useAuth()
+  const navigate = useNavigate()
+
+  if (!email) {
+    return (
+      <Stack spacing={2} direction={'row'}>
+        <Tooltip title={'Create a free account'}>
```
Comment (Saela) [inline src/components/shared/navbar/NavBarUserActions.tsx:18]: Not really a fan of icons only stuff as icons need to be super specific and universal so the user intuitively understands what the icon does. I didn't get the MeetingRoomIcon though XD I think we should revisit this one. ;)

**Review by Saela — COMMENTED** [review]
Not really happy with the icons (especially in desktop mode).  :) But we need to talk about the layout anyways at the end. :) I also think we need to come up with a mobile friendlier way to show the tour list. It's not really usable now because the buttons are initially hidden (you have to scroll) and they are extremely small.

But in general: LGTM ;)

**Comment by Tugark** [comment]
I get your point as discussed :) Let's see tomorrow. 

And for the tour table - yes, or maybe we could add a hint. Also, the dates do not really make sense at all, so we could also just remove them.
